AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  BloggingEvents:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub BloggingEvents-${Env}
      AttributeDefinitions:
        - AttributeName: "ArticleId"
          AttributeType: "S"
        - AttributeName: "EventId"
          AttributeType: "S"
        - AttributeName: "Status" # Try, Confirm, Cancel
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ArticleId"
          KeyType: "HASH"
        - AttributeName: "EventId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      BillingMode: PROVISIONED
      GlobalSecondaryIndexes:
        - IndexName: "Status_EventId-Index"
          KeySchema:
            - AttributeName: "Status"
              KeyType: "HASH"
            - AttributeName: "EventId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  SSMParameterBloggingEventsTableName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/dynamodb/blogging-events/name
      Type: "String"
      Value: !Ref BloggingEvents
      Description: "BloggingEvents TableName"
      Tags:
        Environment: !Ref Env

  SSMParameterBloggingEventsStream:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/dynamodb/blogging-events/stream
      Type: "String"
      Value: !GetAtt BloggingEvents.StreamArn
      Description: "BloggingEvents Stream"
      Tags:
        Environment: !Ref Env
