AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  MiyamoTodayAPIECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub miyamo-today-api-${Env}
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowPushPull"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:GetRepositoryPolicy
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
              - ecr:BatchGetImage
              - ecr:GetLifecyclePolicy
              - ecr:GetLifecyclePolicyPreview
              - ecr:ListTagsForResource
              - ecr:DescribeImageScanFindings
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPIArticleECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub miyamo-today-api-article-service-${Env}
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowPushPull"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:GetRepositoryPolicy
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
              - ecr:BatchGetImage
              - ecr:GetLifecyclePolicy
              - ecr:GetLifecyclePolicyPreview
              - ecr:ListTagsForResource
              - ecr:DescribeImageScanFindings
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPITagECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub miyamo-today-api-tag-service-${Env}
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowPushPull"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:GetRepositoryPolicy
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
              - ecr:BatchGetImage
              - ecr:GetLifecyclePolicy
              - ecr:GetLifecyclePolicyPreview
              - ecr:ListTagsForResource
              - ecr:DescribeImageScanFindings
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPIBloggingEventECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub miyamo-today-api-miyamo-todayging_event-service-${Env}
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowPushPull"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:GetRepositoryPolicy
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
              - ecr:BatchGetImage
              - ecr:GetLifecyclePolicy
              - ecr:GetLifecyclePolicyPreview
              - ecr:ListTagsForResource
              - ecr:DescribeImageScanFindings
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  SSMParameterMiyamoTodayAPIECRRepositoryName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/ecr/miyamo-today-api/name
      Type: "String"
      Value: !Ref MiyamoTodayAPIECRRepository
      Tags:
        Environment: !Ref Env

  SSMParameterMiyamoTodayAPIArticleECRRepositoryName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/ecr/miyamo-today-api-article-service/name
      Type: "String"
      Value: !Ref MiyamoTodayAPIArticleECRRepository
      Tags:
        Environment: !Ref Env

  SSMParameterMiyamoTodayAPITagECRRepositoryName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/ecr/miyamo-today-api-tag-service/name
      Type: "String"
      Value: !Ref MiyamoTodayAPITagECRRepository
      Tags:
        Environment: !Ref Env

  SSMParameterMiyamoTodayAPIBloggingEventECRRepositoryName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/ecr/miyamo-today-api-miyamo-todayging-event-service/name
      Type: "String"
      Value: !Ref MiyamoTodayAPIBloggingEventECRRepository
      Tags:
        Environment: !Ref Env
