AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  Ipv6VPCCidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref VPC

  PublicSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: true
      Ipv6Native: true
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: { Ref: "AWS::Region" }
      VpcId: !Ref VPC
      Ipv6CidrBlock: !Select
        - 0
        - !Cidr
          - !Select
            - 0
            - !GetAtt VPC.Ipv6CidrBlocks
          - 1
          - 64
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Environment"
          Value: !Ref Env
    DependsOn: Ipv6VPCCidrBlock

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachement
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationIpv6CidrBlock: "::/0"
      GatewayId: !Ref InternetGateway

  PublicSubnetOneRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetOne
      RouteTableId: !Ref PublicRouteTable

  MiyamoTodayAPIServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ecs service
      VpcId: !Ref VPC
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPIServiceSecurityGroupIngreesSelf:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref MiyamoTodayAPIServiceSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref MiyamoTodayAPIServiceSecurityGroup

  MiyamoTodayAPIServiceSecurityGroupEgreesAll:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref MiyamoTodayAPIServiceSecurityGroup
      IpProtocol: -1
      CidrIp: "0.0.0.0/0"

  ServiceDiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Sub internal-${Env}
      Vpc: !Ref VPC
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  SSMParameterVpcId:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/vpc/id
      Type: "String"
      Value: !Ref VPC
      Tags:
        Environment: !Ref Env

  SSMParameterMiyamoTodayAPIServiceSecurityGroup:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/ec2/security-group/id
      Type: "String"
      Value: !Ref MiyamoTodayAPIServiceSecurityGroup
      Tags:
        Environment: !Ref Env

  SSMParameterServiceDiscoveryNamespaceId:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/service-discovery/namespace/internal/id
      Type: "String"
      Value: !Ref ServiceDiscoveryNamespace
      Tags:
        Environment: !Ref Env

  SSMParameterServiceDiscoveryNamespaceName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/service-discovery/namespace/internal/name
      Type: "String"
      Value: !Sub internal-${Env}
      Tags:
        Environment: !Ref Env

  SSMParameterPublicSubnetOneId:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/subnet/public/one/id
      Type: "String"
      Value: !Ref PublicSubnetOne
      Tags:
        Environment: !Ref Env
