AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/vpc/id
  PublicSubnetOneId:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/subnet/public/one/id
  ServiceDiscoveryNamespaceId:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/service-discovery/namespace/internal/id
  ServiceDiscoveryNamespaceName:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/service-discovery/namespace/internal/name
  MiyamoTodayAPIServiceSecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/ec2/security-group/id
  MiyamoTodayAPIFederatorECRRepositoryName:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/ecr/federator/name
  MiyamoTodayAPIFederatorECRRepositoryImageTag:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/ecr/federator/tag
  MiyamoTodayAPIArticleECRRepositoryName:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/ecr/article-service/name
  MiyamoTodayAPIArticleECRRepositoryImageTag:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/ecr/article-service/tag
  MiyamoTodayAPITagECRRepositoryName:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/ecr/tag-service/name
  MiyamoTodayAPITagECRRepositoryImageTag:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/ecr/tag-service/tag
  NewRelicAppNameForFederator:
    Type: String
  NewRelicAppNameForArticleService:
    Type: String
  NewRelicAppNameForTagService:
    Type: String
  NewRelicLicenseKey:
    NoEcho: true
    Type: String
  CockroachDBDsnForArticle:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/cockroachdb/dsn/article
  CockroachDBDsnForTag:
    Type: AWS::SSM::Parameter::Value<String>
    NoEcho: true
    Default: /miyamo-today/cicd/dev/cockroachdb/dsn/tag
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  ## Blog Backend Cluster
  BlogBackendECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE_SPOT
      ClusterName: !Sub miyamo-today-backend-cluster-${Env}
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  ## MiyamoTodayAPI Federator
  MiyamoTodayAPITaskFederatorDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub miyamo-today-api-task-${Env}
      Cpu: 256 # 0.25 vCPU
      Memory: 512 # 0.5 GB
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref MiyamoTodayAPITaskFederatorExecutionRole
      ContainerDefinitions:
        - Name: !Sub miyamo-today-api-federator-${Env}
          Cpu: 256 # 0.25 vCPU
          Memory: 512 # 0.5 GB
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${MiyamoTodayAPIFederatorECRRepositoryName}:${MiyamoTodayAPIFederatorECRRepositoryImageTag}
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
          HealthCheck:
            Command:
              - "CMD-SHELL"
              - "curl -f http://localhost/health || exit 1"
            Interval: 8
            Retries: 3
            Timeout: 3
            StartPeriod: 20
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              mode: non-blocking
              max-buffer-size: 25m
              awslogs-create-group: true
              awslogs-group: !Ref MiyamoTodayAPITaskFederatorLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub miyamo-today-api-federator-${Env}
          Environment:
            - Name: NEW_RELIC_CONFIG_APP_NAME
              Value: !Ref NewRelicAppNameForFederator
            - Name: NEW_RELIC_CONFIG_LICENSE
              Value: !Ref NewRelicLicenseKey
            - Name: ARTICLE_SERVICE_ADDRESS
              Value:
                Fn::Sub:
                  - "${SERVICE}.${NAMESPACE}:80"
                  - SERVICE: !GetAtt MiyamoTodayAPIArticleServiceDiscoveryService.Name
                    NAMESPACE: !Ref ServiceDiscoveryNamespaceName
            - Name: TAG_SERVICE_ADDRESS
              Value:
                Fn::Sub:
                  - "${SERVICE}.${NAMESPACE}:80"
                  - SERVICE: !GetAtt MiyamoTodayAPITagServiceDiscoveryService.Name
                    NAMESPACE: !Ref ServiceDiscoveryNamespaceName
            - Name: PORT
              Value: "80"
      Tags:
        - Key: "Environment"
          Value: !Ref Env
    DependsOn:
      - MiyamoTodayAPIArticleTaskDefinition
      - MiyamoTodayAPITagTaskDefinition

  MiyamoTodayAPITaskFederatorExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ["sts:AssumeRole"]
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      # Path: /user-defined/ must be root
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPIFederatorServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: !Sub miyamo-today-api-service-discovery-${Env}
      DnsConfig:
        NamespaceId: !Ref ServiceDiscoveryNamespaceId
        DnsRecords:
          - TTL: 300
            Type: SRV
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPIECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub miyamo-today-api-ecs-service-${Env}
      Cluster: !Ref BlogBackendECSCluster
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref MiyamoTodayAPIServiceSecurityGroup
          Subnets:
            - !Ref PublicSubnetOneId
      #DeploymentConfiguration:
      #  MaximumPercent: 200
      #  MinimumHealthyPercent: 75
      DesiredCount: 1
      TaskDefinition: !Ref MiyamoTodayAPITaskFederatorDefinition
      ServiceRegistries:
        - RegistryArn: !GetAtt MiyamoTodayAPIFederatorServiceDiscoveryService.Arn
          Port: 80
      Tags:
        - Key: "Environment"
          Value: !Ref Env
    DependsOn:
      - MiyamoTodayAPIArticleECSService
      - MiyamoTodayAPITagECSService

  MiyamoTodayAPITaskFederatorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/logs/miyamo-today-api-federator-${Env}
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  ## MiyamoTodayAPI-Article-Service
  MiyamoTodayAPIArticleTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub miyamo-today-api-article-service-task-${Env}
      Cpu: 256 # 0.25 vCPU
      Memory: 512 # 0.5 GB
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref MiyamoTodayAPIArticleTaskExecutionRole
      ContainerDefinitions:
        - Name: !Sub miyamo-today-api-article-service-${Env}
          Cpu: 256 # 0.25 vCPU
          Memory: 512 # 0.5 GB
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${MiyamoTodayAPIArticleECRRepositoryName}:${MiyamoTodayAPIArticleECRRepositoryImageTag}
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
          HealthCheck:
            Command:
              - "CMD-SHELL"
              - "/bin/grpc_health_probe -addr=:80 || exit 1"
            Interval: 8
            Retries: 3
            Timeout: 3
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              mode: non-blocking
              max-buffer-size: 25m
              awslogs-create-group: true
              awslogs-group: !Ref MiyamoTodayAPIArticleTaskLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub miyamo-today-api-article-service-${Env}
          Environment:
            - Name: COCKROACHDB_DSN
              Value: !Ref CockroachDBDsnForArticle
            - Name: SERVICE_NAME
              Value: "ArticleService"
            - Name: NEW_RELIC_CONFIG_APP_NAME
              Value: !Ref NewRelicAppNameForArticleService
            - Name: NEW_RELIC_CONFIG_LICENSE
              Value: !Ref NewRelicLicenseKey
            - Name: PORT
              Value: "80"
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPIArticleTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ["sts:AssumeRole"]
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      # Path: /user-defined/ must be root
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPIArticleServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: !Sub miyamo-today-api-article-service-service-discovery-${Env}
      DnsConfig:
        NamespaceId: !Ref ServiceDiscoveryNamespaceId
        DnsRecords:
          - TTL: 300
            Type: A
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPIArticleECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub miyamo-today-api-article-service-ecs-service-${Env}
      Cluster: !Ref BlogBackendECSCluster
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref MiyamoTodayAPIServiceSecurityGroup
          Subnets:
            - !Ref PublicSubnetOneId
      #DeploymentConfiguration:
      #  MaximumPercent: 200
      #  MinimumHealthyPercent: 75
      DesiredCount: 1
      TaskDefinition: !Ref MiyamoTodayAPIArticleTaskDefinition
      ServiceRegistries:
        - RegistryArn: !GetAtt MiyamoTodayAPIArticleServiceDiscoveryService.Arn
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPIArticleTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/logs/miyamo-today-api-article-service-${Env}
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  ## MiyamoTodayAPI-Tag-Service
  MiyamoTodayAPITagTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub miyamo-today-api-tag-service-task-${Env}
      Cpu: 256 # 0.25 vCPU
      Memory: 512 # 0.5 GB
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref MiyamoTodayAPITagTaskExecutionRole
      ContainerDefinitions:
        - Name: !Sub miyamo-today-api-tag-service-${Env}
          Cpu: 256 # 0.25 vCPU
          Memory: 512 # 0.5 GB
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${MiyamoTodayAPITagECRRepositoryName}:${MiyamoTodayAPITagECRRepositoryImageTag}
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
          HealthCheck:
            Command:
              - "CMD-SHELL"
              - "/bin/grpc_health_probe -addr=:80 || exit 1"
            Interval: 8
            Retries: 3
            Timeout: 3
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              mode: non-blocking
              max-buffer-size: 25m
              awslogs-create-group: true
              awslogs-group: !Ref MiyamoTodayAPITagTaskLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub miyamo-today-api-tag-service-${Env}
          Environment:
            - Name: COCKROACHDB_DSN
              Value: !Ref CockroachDBDsnForTag
            - Name: SERVICE_NAME
              Value: "TagService"
            - Name: NEW_RELIC_CONFIG_APP_NAME
              Value: !Ref NewRelicAppNameForTagService
            - Name: NEW_RELIC_CONFIG_LICENSE
              Value: !Ref NewRelicLicenseKey
            - Name: PORT
              Value: "80"
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPITagTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ["sts:AssumeRole"]
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      # Path: /user-defined/ must be root
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPITagServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: !Sub miyamo-today-api-tag-service-service-discovery-${Env}
      DnsConfig:
        NamespaceId: !Ref ServiceDiscoveryNamespaceId
        DnsRecords:
          - TTL: 300
            Type: A
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPITagECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub miyamo-today-api-tag-service-ecs-service-${Env}
      Cluster: !Ref BlogBackendECSCluster
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref MiyamoTodayAPIServiceSecurityGroup
          Subnets:
            - !Ref PublicSubnetOneId
      #DeploymentConfiguration:
      #  MaximumPercent: 200
      #  MinimumHealthyPercent: 75
      DesiredCount: 1
      TaskDefinition: !Ref MiyamoTodayAPITagTaskDefinition
      ServiceRegistries:
        - RegistryArn: !GetAtt MiyamoTodayAPITagServiceDiscoveryService.Arn
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  MiyamoTodayAPITagTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/logs/miyamo-today-api-tag-service-${Env}
      Tags:
        - Key: "Environment"
          Value: !Ref Env

  SSMParameterMiyamoTodayAPIFederatorServiceDiscoveryServiceArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Tier: "Standard"
      Name: !Sub /miyamo-today/cicd/${Env}/service-discovery/miyamo-today-api/arn
      Type: "String"
      Value: !GetAtt MiyamoTodayAPIFederatorServiceDiscoveryService.Arn
      Tags:
        Environment: !Ref Env
