name: deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - update_miyamo-today-api-federator_ecr
      - update_miyamo-today-api-article_ecr
      - update_miyamo-today-api-tag_ecr
      - update_miyamo-today-api-blogging-event_ecr
  workflow_dispatch:

permissions: write-all

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main

      - name: Set up aws cli
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          mask-aws-account-id: true

      - name: Deploy AWS VPC
        working-directory: ./aws/vpc
        run: |
          sam package --output-template-file packaged.yaml --s3-bucket ${{ secrets.SAM_ARTIFACTS_BUCKET_NAME }}
          sam deploy --template-file packaged.yaml --stack-name miyamo-today-cloud-infra-vpc-prod --capabilities CAPABILITY_IAM \
            --parameter-overrides \
            Env=prod \
            --no-fail-on-empty-changeset

      - name: Deploy AWS ECR
        working-directory: ./aws/ecr
        run: |
          sam package --output-template-file packaged.yaml --s3-bucket ${{ secrets.SAM_ARTIFACTS_BUCKET_NAME }}
          sam deploy --template-file packaged.yaml --stack-name miyamo-today-cloud-infra-ecr-prod --capabilities CAPABILITY_IAM \
            --parameter-overrides \
            Env=prod \
            --no-fail-on-empty-changeset

      - name: Deploy AWS ECS
        working-directory: ./aws/ecs
        run: |
          if ssm get-parameters --names /miyamo-today/cicd/prod/ecr/article-service/tag --output text --query Parameters[0].Value | grep "None"; then
            exit 0
          fi
          if ssm get-parameters --names /miyamo-today/cicd/prod/ecr/tag-service/tag --output text --query Parameters[0].Value | grep "None"; then
            exit 0
          fi
          if ssm get-parameters --names /miyamo-today/cicd/prod/ecr/blogging-event-service/tag --output text --query Parameters[0].Value | grep "None"; then
            exit 0
          fi
          if aws ssm get-parameters --names /miyamo-today/cicd/prod/ecr/federator/tag --output text --query Parameters[0].Value | grep "None"; then
            exit 0
          fi
          sam package --output-template-file packaged.yaml --s3-bucket ${{ secrets.SAM_ARTIFACTS_BUCKET_NAME }}
          sam deploy --template-file packaged.yaml --stack-name miyamo-today-cloud-infra-ecs-prod --capabilities CAPABILITY_IAM \
            --parameter-overrides \
            Env=prod \
            NewRelicAppNameForFederator=miyamo-today-api-federator-prod \
            NewRelicAppNameForArticleService=miyamo-today-api-article-service-prod \
            NewRelicAppNameForTagService=miyamo-today-api-tag-service-prod \
            NewRelicAppNameForBloggingEventService=miyamo-today-api-blogging-event-service-prod \
            NewRelicLicenseKey=${{ secrets.NEW_RELIC_LICENSE_KEY }} \
            S3BucketForImage=${{ secrets.S3_BUCKET_FOR_IMAGE }} \
            CDNHostForImage=${{ secrets.CDN_HOST_FOR_IMAGE }} \
            VpcId=/miyamo-today/cicd/prod/vpc/id \
            PublicSubnetOneId=/miyamo-today/cicd/prod/subnet/public/one/id \
            ServiceDiscoveryNamespaceId=/miyamo-today/cicd/prod/service-discovery/namespace/internal/id \
            ServiceDiscoveryNamespaceName=/miyamo-today/cicd/prod/service-discovery/namespace/internal/name \
            MiyamoTodayAPIServiceSecurityGroup=/miyamo-today/cicd/prod/ec2/security-group/id \
            MiyamoTodayAPIFederatorECRRepositoryName=/miyamo-today/cicd/prod/ecr/federator/name \
            MiyamoTodayAPIFederatorECRRepositoryImageTag=/miyamo-today/cicd/prod/ecr/federator/tag \
            MiyamoTodayAPIArticleECRRepositoryName=/miyamo-today/cicd/prod/ecr/article-service/name \
            MiyamoTodayAPIArticleECRRepositoryImageTag=/miyamo-today/cicd/prod/ecr/article-service/tag \
            MiyamoTodayAPITagECRRepositoryName=/miyamo-today/cicd/prod/ecr/tag-service/name \
            MiyamoTodayAPITagECRRepositoryImageTag=/miyamo-today/cicd/prod/ecr/tag-service/tag \
            MiyamoTodayAPIBloggingEventECRRepositoryName=/miyamo-today/cicd/prod/ecr/blogging-event-service/name \
            MiyamoTodayAPIBloggingEventECRRepositoryImageTag=/miyamo-today/cicd/prod/ecr/blogging-event-service/tag \
            CockroachDBDsnForArticle=/miyamo-today/cicd/prod/cockroachdb/dsn/article \
            CockroachDBDsnForTag=/miyamo-today/cicd/prod/cockroachdb/dsn/tag \
            BloggingEventsTableName=/miyamo-today/cicd/prod/dynamodb/blogging-events/name \
            --no-fail-on-empty-changeset \

      - name: Deploy AWS API Gateway
        working-directory: ./aws/api-gateway
        run: |
          if aws ssm get-parameters --names /miyamo-today/cicd/prod/service-discovery/miyamo-today-api/arn --output text --query Parameters[0].Value | grep "None"; then
            exit 0
          fi
          sam package --output-template-file packaged.yaml --s3-bucket ${{ secrets.SAM_ARTIFACTS_BUCKET_NAME }}
          sam deploy --template-file packaged.yaml --stack-name miyamo-today-cloud-infra-api-gateway-prod --capabilities CAPABILITY_IAM \
            --parameter-overrides \
            Env=prod \
            VpcId=/miyamo-today/cicd/prod/vpc/id \
            PublicSubnetOneId=/miyamo-today/cicd/prod/subnet/public/one/id \
            MiyamoTodayAPIServiceSecurityGroup=/miyamo-today/cicd/prod/ec2/security-group/id \
            MiyamoTodayAPIServiceDiscoveryServiceArn=/miyamo-today/cicd/prod/service-discovery/miyamo-today-api/arn \
            CognitoUserPoolId=/miyamo-today/cicd/prod/cognito/user-pool/id \
            CognitoUserPoolClientId=/miyamo-today/cicd/prod/cognito/user-pool-client/id \
            --no-fail-on-empty-changeset
